# Generated by Django 5.2.8 on 2025-11-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_term_image_term_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='image',
        ),
        migrations.RemoveField(
            model_name='term',
            name='video',
        ),
        migrations.AddField(
            model_name='term',
            name='image_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к изображению в static'),
        ),
        migrations.AddField(
            model_name='term',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/', verbose_name='Загрузить изображение'),
        ),
        migrations.AddField(
            model_name='term',
            name='video_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Путь к видео в static'),
        ),
        migrations.AddField(
            model_name='term',
            name='video_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/', verbose_name='Загрузить видео'),
        ),
        migrations.AlterField(
            model_name='term',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
